credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: # Placeholder for hashed password of 'abc'
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: # Placeholder for hashed password of 'def'
cookie:
  expiry_days: 0
  key: "Platinum79" # Must be string
  name: "Platinum79"
preauthorized:
  emails:
  - jeggino@gmail.com
