cookie:
  expiry_days: 30
  key: ceppo
  name: capocchia
credentials:
  usernames:
    luigi:
      email: dbaldwin@gmail.com
      logged_in: False
      name: Luigi Giugliano
      password: Platinum_79
preauthorized:
  emails: melsby@gmail.com
