cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    luigi:
      email: dbaldwin@gmail.com
      logged_in: False
      name: Luigi Giugliano
      password: Platinum_79
preauthorized:
  emails: melsby@gmail.com
