credentials:
  usernames:
    jsmith:
      email: jeggino@gmail.com
      logged_in: False # Will be managed automatically
      name: Luigi
      password: Platinum_79 # Will be hashed automatically
    rbriggs:
      email: rbriggs@gmail.com
      logged_in: True # Will be managed automatically
      name: Rebecca Briggs
      password: def # Will be hashed automatically
cookie:
  expiry_days: 0
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
