credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: 'abc'
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: 'def'
cookie:
  expiry_days: 0
  key: "Platinum79" # Must be string
  name: "Platinum79"
preauthorized:
  emails:
  - jeggino@gmail.com

hashed_passwords = stauth.Hasher(['abc', 'def']).generate()
